In [ ]:
### KNN Regression
    ### MAE
    ### MSE
    ### RMSE
    ### R2
    ### MAPE
#### KNN Classification
### confusion matrix
### precision
### recall
### f1 score
### accuracy score, error percentage

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
import pandas as pd
import numpy as np
df=pd.DataFrame(np.random.randint(0,10,(100,4)),columns=['age','salary','#ofmembers','emi'])

In [ ]:
df['age']=np.random.randint(18,100,100)
df['salary']=np.random.randint(100000,200000,100)
df['#ofmembers']=np.random.randint(1,8,100)
df['emi']=np.random.randint(0,2,100)

In [ ]:
df['emi'].value_counts()

emi
1    50
0    50
Name: count, dtype: int64

In [ ]:
df.columns

Index(['age', 'salary', '#ofmembers', 'emi'], dtype='object')

In [ ]:
y=df['emi']
x=df.drop('emi',axis=1)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
print(x_train.shape,y_test.shape,x_test.shape,y_train.shape)

(80, 3) (20,) (20, 3) (80,)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
kn=KNeighborsClassifier()
kn.fit(x_train,y_train)
kn.predict(x_test)

array([1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1])

In [ ]:
y_test.values

array([1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1])

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test.values,kn.predict(x_test))

array([[ 2, 11],
       [ 2,  5]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test.values,kn.predict(x_test))

0.35

In [ ]:
7/20

0.35

In [ ]:
TN FP
FN TP

In [ ]:
TP
FN
FP
TN`

In [ ]:
TN,FP,FN,TP=confusion_matrix(y_test.values,kn.predict(x_test)).ravel()
accuracy = (TP + TN) / (TP + TN + FP + FN)

precision = TP / (TP + FP)

recall = TP / (TP + FN)

specificity = TN / (TN + FP)

f1 = 2 * precision * recall / (precision + recall)

print("Accuracy    :", accuracy)
print("Precision   :", precision)
print("Recall      :", recall)
print("Specificity :", specificity)
print("F1 Score    :", f1)

Accuracy    : 0.35
Precision   : 0.3125
Recall      : 0.7142857142857143
Specificity : 0.15384615384615385
F1 Score    : 0.43478260869565216

In [ ]:
The model correctly predicts 35 out of
every 100 observations overall.
This indicates low overall predictive performance.

In [ ]:
Of all observations predicted as positive (1),
 only 31.25% are actually positive.
The model is producing many false positives.

In [ ]:
Of all the actual positive cases, the model correctly
identifies 71.43%.
This is relatively stronger than the other metrics.

In [ ]:
The balance between precision and recall is 43.48%.
The low F1 score is mainly due to the low precision

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
kn=KNeighborsClassifier()
kn.fit(x_train,y_train)
kn.predict(x_test)
TN,FP,FN,TP=confusion_matrix(y_test.values,kn.predict(x_test)).ravel()
accuracy = (TP + TN) / (TP + TN + FP + FN)
precision = TP / (TP + FP)
recall = TP / (TP + FN)
specificity = TN / (TN + FP)
f1 = 2 * precision * recall / (precision + recall)
print("Accuracy    :", accuracy)
print("Precision   :", precision)
print("Recall      :", recall)
print("Specificity :", specificity)
print("F1 Score    :", f1)

Accuracy    : 0.35
Precision   : 0.3125
Recall      : 0.7142857142857143
Specificity : 0.15384615384615385
F1 Score    : 0.43478260869565216

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
kn=KNeighborsClassifier(n_neighbors=8)
kn.fit(x_train,y_train)
kn.predict(x_test)
TN,FP,FN,TP=confusion_matrix(y_test.values,kn.predict(x_test)).ravel()
accuracy = (TP + TN) / (TP + TN + FP + FN)
precision = TP / (TP + FP)
recall = TP / (TP + FN)
specificity = TN / (TN + FP)
f1 = 2 * precision * recall / (precision + recall)
print("Accuracy    :", accuracy)
print("Precision   :", precision)
print("Recall      :", recall)
print("Specificity :", specificity)
print("F1 Score    :", f1)

Accuracy    : 0.45
Precision   : 0.25
Recall      : 0.2857142857142857
Specificity : 0.5384615384615384
F1 Score    : 0.26666666666666666

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
def neighbors_algo(n):
  kn=KNeighborsClassifier(n_neighbors=n)
  kn.fit(x_train,y_train)
  kn.predict(x_test)
  TN,FP,FN,TP=confusion_matrix(y_test.values,kn.predict(x_test)).ravel()
  accuracy = (TP + TN) / (TP + TN + FP + FN)
  precision = TP / (TP + FP)
  recall = TP / (TP + FN)
  specificity = TN / (TN + FP)
  f1 = 2 * precision * recall / (precision + recall)
  print("Accuracy    :", accuracy)
  print("Precision   :", precision)
  print("Recall      :", recall)
  print("Specificity :", specificity)
  print("F1 Score    :", f1)
  return "Neighbors "+str(n),accuracy,precision,recall,f1

In [ ]:
accuracy_score_matrix=[]
for i in range(1,11):
  accuracy_score_matrix.append(neighbors_algo(i))

Accuracy    : 0.3
Precision   : 0.26666666666666666
Recall      : 0.5714285714285714
Specificity : 0.15384615384615385
F1 Score    : 0.36363636363636365
Accuracy    : 0.4
Precision   : 0.14285714285714285
Recall      : 0.14285714285714285
Specificity : 0.5384615384615384
F1 Score    : 0.14285714285714285
Accuracy    : 0.45
Precision   : 0.3333333333333333
Recall      : 0.5714285714285714
Specificity : 0.38461538461538464
F1 Score    : 0.4210526315789474
Accuracy    : 0.45
Precision   : 0.25
Recall      : 0.2857142857142857
Specificity : 0.5384615384615384
F1 Score    : 0.26666666666666666
Accuracy    : 0.35
Precision   : 0.3125
Recall      : 0.7142857142857143
Specificity : 0.15384615384615385
F1 Score    : 0.43478260869565216
Accuracy    : 0.4
Precision   : 0.3076923076923077
Recall      : 0.5714285714285714
Specificity : 0.3076923076923077
F1 Score    : 0.4
Accuracy    : 0.4
Precision   : 0.35294117647058826
Recall      : 0.8571428571428571
Specificity : 0.15384615384615385
F1 Score    : 0.5
Accuracy    : 0.45
Precision   : 0.25
Recall      : 0.2857142857142857
Specificity : 0.5384615384615384
F1 Score    : 0.26666666666666666
Accuracy    : 0.45
Precision   : 0.3
Recall      : 0.42857142857142855
Specificity : 0.46153846153846156
F1 Score    : 0.3529411764705882
Accuracy    : 0.55
Precision   : 0.375
Recall      : 0.42857142857142855
Specificity : 0.6153846153846154
F1 Score    : 0.39999999999999997

In [ ]:
accuracy_score_matrix=pd.DataFrame(accuracy_score_matrix)
accuracy_score_matrix.columns=['Neighbors','accuracy','precision','recall','f1']

In [ ]:
accuracy_score_matrix

      Neighbors  accuracy  precision    recall        f1
0   Neighbors 1      0.30   0.266667  0.571429  0.363636
1   Neighbors 2      0.40   0.142857  0.142857  0.142857
2   Neighbors 3      0.45   0.333333  0.571429  0.421053
3   Neighbors 4      0.45   0.250000  0.285714  0.266667
4   Neighbors 5      0.35   0.312500  0.714286  0.434783
5   Neighbors 6      0.40   0.307692  0.571429  0.400000
6   Neighbors 7      0.40   0.352941  0.857143  0.500000
7   Neighbors 8      0.45   0.250000  0.285714  0.266667
8   Neighbors 9      0.45   0.300000  0.428571  0.352941
9  Neighbors 10      0.55   0.375000  0.428571  0.400000

In [ ]:
# ============================================================
# KNN REGRESSION - COMPLETE CODE
# ============================================================

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


# ------------------------------------------------------------
# 1. Create Dummy Dataset
# ------------------------------------------------------------

df = pd.DataFrame()

df['age'] = np.random.randint(18, 70, 100)

df['salary'] = np.random.randint(
    100000,
    200000,
    100
)

df['#ofmembers'] = np.random.randint(
    1,
    8,
    100
)

# EMI is continuous because this is regression
df['emi'] = np.random.randint(
    5000,
    50000,
    100
)


print("Dataset:")
print(df.head())


# ------------------------------------------------------------
# 2. Independent Variables
# ------------------------------------------------------------

x = df[
    [
        'age',
        'salary',
        '#ofmembers'
    ]
]


# ------------------------------------------------------------
# 3. Dependent Variable
# ------------------------------------------------------------

y = df['emi']


# ------------------------------------------------------------
# 4. Train Test Split
# ------------------------------------------------------------

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)


# ------------------------------------------------------------
# 5. KNN Regression Function
# ------------------------------------------------------------

def neighbors_algo(n):

    # Create KNN Regressor
    kn = KNeighborsRegressor(
        n_neighbors=n
    )


    # Train the model
    kn.fit(
        x_train,
        y_train
    )


    # Prediction
    y_pred = kn.predict(x_test)


    # --------------------------------------------------------
    # Regression Metrics
    # --------------------------------------------------------

    # Mean Absolute Error
    mae = mean_absolute_error(
        y_test,
        y_pred
    )


    # Mean Squared Error
    mse = mean_squared_error(
        y_test,
        y_pred
    )


    # Root Mean Squared Error
    rmse = np.sqrt(mse)


    # R2 Score
    r2 = r2_score(
        y_test,
        y_pred
    )


    # --------------------------------------------------------
    # Print Results
    # --------------------------------------------------------

    print("\nNeighbors :", n)

    print("MAE  :", mae)

    print("MSE  :", mse)

    print("RMSE :", rmse)

    print("R2   :", r2)


    # Return Results
    return (
        "Neighbors " + str(n),
        mae,
        mse,
        rmse,
        r2
    )


# ------------------------------------------------------------
# 6. Test Different K Values
# ------------------------------------------------------------

neighbors_algo(3)

neighbors_algo(5)

neighbors_algo(7)

neighbors_algo(9)

Dataset:
   age  salary  #ofmembers    emi
0   52  111794           1   7161
1   65  143200           2   9264
2   56  176452           1  18093
3   26  153970           6  44687
4   30  179047           3  46774

Neighbors : 3
MAE  : 10864.06666666667
MSE  : 174400833.6666667
RMSE : 13206.090779131677
R2   : 0.06797244857643048

Neighbors : 5
MAE  : 11187.810000000001
MSE  : 158472658.854
RMSE : 12588.592409558743
R2   : 0.15309530869802035

Neighbors : 7
MAE  : 10963.142857142857
MSE  : 161648069.83877552
RMSE : 12714.08942232103
R2   : 0.13612537534001534

Neighbors : 9
MAE  : 11148.972222222223
MSE  : 169302713.14012346
RMSE : 13011.637604088251
R2   : 0.09521766691235922

('Neighbors 9',
 11148.972222222223,
 169302713.14012346,
 np.float64(13011.637604088251),
 0.09521766691235922)

In [ ]:
#### Manual hyper parameter tuning by using UDF
#### Automatic Hyperparameter tuning using GridSearchCV

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
parameters={
    'n_neighbors':[3,4,5,6,7,8,9],
    'metrics':['euclidean','manhattan']
}

In [ ]:
grid=GridSearchCV(estimator=kn,param_grid=parameters,cv=5,scoring='accuracy')

In [ ]:
KNeighborsClassifier

sklearn.neighbors._classification.KNeighborsClassifier

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix


# ============================================================
# 1. CREATE DUMMY DATASET
# ============================================================

np.random.seed(42)

df = pd.DataFrame()

df['age'] = np.random.randint(18, 70, 100)

df['salary'] = np.random.randint(100000, 200000, 100)

df['#ofmembers'] = np.random.randint(1, 8, 100)

# Target
# 0 = No
# 1 = Yes
df['emi'] = np.random.randint(0, 2, 100)


print("Dataset:")
print(df.head())

print("\nDataset Shape:")
print(df.shape)

print("\nNull Values:")
print(df.isnull().sum())


# ============================================================
# 2. DEFINE X AND Y
# ============================================================

x = df[
    [
        'age',
        'salary',
        '#ofmembers'
    ]
]

y = df['emi']


# ============================================================
# 3. TRAIN TEST SPLIT
# ============================================================

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)


# ============================================================
# 4. FEATURE SCALING
# ============================================================

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)

x_test = scaler.transform(x_test)


# ============================================================
# 5. CREATE KNN CLASSIFIER
# ============================================================

kn = KNeighborsClassifier()


# ============================================================
# 6. GRID SEARCH PARAMETERS
# ============================================================

parameters = {

    'n_neighbors': [
        3,
        5,
        7,
        9,
        11
    ],

    'weights': [
        'uniform',
        'distance'
    ],

    'metric': [
        'euclidean',
        'manhattan',
        'minkowski'
    ],

    'p': [
        1,
        2
    ]
}


# ============================================================
# 7. CREATE GRIDSEARCHCV
# ============================================================

grid = GridSearchCV(
    estimator=kn,
    param_grid=parameters,
    cv=5,
    scoring='accuracy'
)


# ============================================================
# 8. TRAIN GRIDSEARCH
# ============================================================

grid.fit(
    x_train,
    y_train
)


# ============================================================
# 9. BEST PARAMETERS
# ============================================================

print("\nBest Parameters:")

print(
    grid.best_params_
)


# ============================================================
# 10. BEST CROSS VALIDATION SCORE
# ============================================================

print("\nBest Cross Validation Accuracy:")

print(
    grid.best_score_
)


# ============================================================
# 11. GET BEST MODEL
# ============================================================

best_kn = grid.best_estimator_

print("\nBest KNN Model:")

print(best_kn)


# ============================================================
# 12. PREDICTION
# ============================================================

y_pred = best_kn.predict(
    x_test
)


print("\nActual Values:")

print(
    y_test.values
)


print("\nPredicted Values:")

print(
    y_pred
)


# ============================================================
# 13. CONFUSION MATRIX
# ============================================================

cm = confusion_matrix(
    y_test.values,
    y_pred
)

print("\nConfusion Matrix:")

print(cm)


# ============================================================
# 14. EXTRACT TN, FP, FN, TP
# ============================================================

TN, FP, FN, TP = cm.ravel()


print("\nTN =", TN)

print("FP =", FP)

print("FN =", FN)

print("TP =", TP)


# ============================================================
# 15. CALCULATE METRICS MANUALLY
# ============================================================

# Accuracy
accuracy = (
    (TP + TN)
    /
    (TP + TN + FP + FN)
)


# Precision
precision = (
    TP
    /
    (TP + FP)
)


# Recall / Sensitivity
recall = (
    TP
    /
    (TP + FN)
)


# Specificity
specificity = (
    TN
    /
    (TN + FP)
)


# F1 Score
f1 = (
    2 * precision * recall
    /
    (precision + recall)
)


# False Positive Rate
fpr = (
    FP
    /
    (FP + TN)
)


# False Negative Rate
fnr = (
    FN
    /
    (FN + TP)
)


# Negative Predictive Value
npv = (
    TN
    /
    (TN + FN)
)


# ============================================================
# 16. PRINT ALL METRICS
# ============================================================

print("\n========== FINAL MODEL METRICS ==========")

print("Accuracy    :", accuracy)

print("Precision   :", precision)

print("Recall      :", recall)

print("Specificity :", specificity)

print("F1 Score    :", f1)

print("FPR         :", fpr)

print("FNR         :", fnr)

print("NPV         :", npv)


# ============================================================
# 17. PRINT METRICS AS PERCENTAGE
# ============================================================

print("\n========== METRICS IN PERCENTAGE ==========")

print(
    "Accuracy    :",
    round(accuracy * 100, 2),
    "%"
)

print(
    "Precision   :",
    round(precision * 100, 2),
    "%"
)

print(
    "Recall      :",
    round(recall * 100, 2),
    "%"
)

print(
    "Specificity :",
    round(specificity * 100, 2),
    "%"
)

print(
    "F1 Score    :",
    round(f1 * 100, 2),
    "%"
)


# ============================================================
# 18. PREDICT NEW CUSTOMER
# ============================================================

new_customer = pd.DataFrame(
    {
        'age': [35],
        'salary': [150000],
        '#ofmembers': [4]
    }
)


# Apply same scaler
new_customer_scaled = scaler.transform(
    new_customer
)


# Make prediction
prediction = best_kn.predict(
    new_customer_scaled
)


print("\nNew Customer Prediction:")

print(
    prediction[0]
)


if prediction[0] == 1:

    print("Customer belongs to EMI = YES")

else:

    print("Customer belongs to EMI = NO")

Dataset:
   age  salary  #ofmembers  emi
0   56  161228           3    0
1   69  148984           6    0
2   46  140774           1    0
3   32  102568           4    1
4   60  162592           1    1

Dataset Shape:
(100, 4)

Null Values:
age           0
salary        0
#ofmembers    0
emi           0
dtype: int64

Best Parameters:
{'metric': 'euclidean', 'n_neighbors': 7, 'p': 1, 'weights': 'distance'}

Best Cross Validation Accuracy:
0.55

Best KNN Model:
KNeighborsClassifier(metric='euclidean', n_neighbors=7, p=1, weights='distance')

Actual Values:
[1 1 1 1 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 1]

Predicted Values:
[1 1 1 1 1 0 1 0 0 0 1 0 0 0 1 1 1 1 0 0]

Confusion Matrix:
[[4 5]
 [5 6]]

TN = 4
FP = 5
FN = 5
TP = 6

========== FINAL MODEL METRICS ==========
Accuracy    : 0.5
Precision   : 0.5454545454545454
Recall      : 0.5454545454545454
Specificity : 0.4444444444444444
F1 Score    : 0.5454545454545454
FPR         : 0.5555555555555556
FNR         : 0.45454545454545453
NPV         : 0.4444444444444444

========== METRICS IN PERCENTAGE ==========
Accuracy    : 50.0 %
Precision   : 54.55 %
Recall      : 54.55 %
Specificity : 44.44 %
F1 Score    : 54.55 %

New Customer Prediction:
1
Customer belongs to EMI = YES

In [ ]:
#### K fold validation and cross validation

In [ ]:
Ensmble model